version: '3'

services:
  media-server:
    build: .
    restart: unless-stopped
    network_mode: host
#    ports:
#      - 10000:10000
#      - 10001:10001
#      - 40927:4000/tcp
#      - 40927:4000/udp
