version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./http/:/etc/nginx/http:ro
      - ./https/:/etc/nginx/https:ro
      - ./www/:/usr/share/nginx/html:ro
      - /home/docker/phasmophobia-cheatsheet/build/:/usr/share/nginx/phasmophobia-cheatsheet:ro
    restart: always
    networks:
      - web

networks:
  web:
