version: "3.2"
services:
  prowlarr:
    container_name: prowlarr
    image: cr.hotio.dev/hotio/prowlarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr:/config
      - /home/alex/Media/:/data
      - ./downloads:/downloads
    networks:
      - nginx_web
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config
      - /home/alex/Media/:/data
      - ./downloads:/downloads
    networks:
      - nginx_web
  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Detroit
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config
      - /home/alex/Media/:/data
      - ./downloads:/downloads
    networks:
      - nginx_web
  lidarr:
    container_name: lidarr
    image: cr.hotio.dev/hotio/lidarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./lidarr:/config
      - /home/alex/Media/:/media/data
      - ./downloads:/downloads
    networks:
      - nginx_web

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent:/config
      - ./downloads:/downloads
    restart: unless-stopped
    ports:
      - 6881:6881
    networks:
      - nginx_web
networks:
  nginx_web:
    external: true
